services:
  rsync-parser:
    build: ./parser
    volumes:
      - ./rsyncd.log:/var/log/rsyncd.log:ro
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - HASH_SALT=change_this_salt_in_production
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
