# sudo-eopkg-Vanguard: Hardened Perimeter Security Stack
# Government-grade aligned (Zero Trust, OSS-based)



services:

  eopkg-BunkerWeb:
    image: bunkerity/bunkerweb:latest
    container_name: eopkg-BunkerWeb
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/sudo-eopkg-Vanguard/eopkg-BunkerWeb:/etc/bunkerweb
      - ./docker/sudo-eopkg-CertbotCloudflare/conf:/etc/letsencrypt:ro
    environment:
      - BUNKERWEB_CERT_PATH=/etc/letsencrypt/live/aptlantis.net/fullchain.pem
      - BUNKERWEB_KEY_PATH=/etc/letsencrypt/live/aptlantis.net/privkey.pem
    networks:
      - sudo-eopkg-Vanguard

  eopkg-BunkewWebUI:
    image: bunkerity/bunkerweb-ui:latest
    container_name: eopkg-BunkewWebUI
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - BUNKERWEB_API_URL=http://eopkg-BunkerWeb:10101
    volumes:
      - ./docker/sudo-eopkg-Vanguard/eopkg-BunkerWebUI:/etc/bunkerweb-ui
    networks:
      - sudo-eopkg-Vanguard


  eopkg-CertbotCloudflare:
    image: certbot/dns-cloudflare
    container_name: eopkg-CertbotCloudflare
    volumes:
      - ./docker/sudo-eopkg-CertbotCloudflare/conf:/etc/letsencrypt
      - ./docker/sudo-eopkg-CertbotCloudflare/cloudflare:/cloudflare
    environment:
      - CLOUDFLARE_EMAIL=your@email.com
      - CLOUDFLARE_API_KEY=your_global_api_key
    command: >
      certonly --dns-cloudflare \
      --dns-cloudflare-credentials /cloudflare/credentials.ini \
      -d '*.aptlantis.net' -d aptlantis.net \
      --agree-tos --no-eff-email --non-interactive
    networks:
      - sudo-eopkg-Vanguard

  eopkg-CrowdSec:
    image: crowdsecurity/crowdsec
    container_name: eopkg-CrowdSec
    volumes:
      - ./docker/sudo-eopkg-Vanguard/eopkg-CrowdSec:/etc/crowdsec
      - /var/log:/var/log:ro
    networks:
      - sudo-eopkg-Vanguard
    restart: unless-stopped

  eopkg-CrowdSecBouncer:
    image: crowdsecurity/cs-firewall-bouncer
    container_name: eopkg-CrowdSecBouncer
    environment:
      - CROWDSEC_LAPI_URL=http://eopkg-CrowdSec:8080
      - CROWDSEC_LAPI_KEY=YOUR_BOUNCER_API_KEY
    networks:
      - sudo-eopkg-Vanguard
    restart: unless-stopped

  eopkg-Fail2Ban:
    image: crazymax/fail2ban:latest
    container_name: eopkg-Fail2Ban
    volumes:
      - ./docker/sudo-eopkg-Vanguard/eopkg-Fail2Ban:/data
      - /var/log:/var/log:ro
    environment:
      - TZ=UTC
    networks:
      - sudo-eopkg-Vanguard
    restart: unless-stopped

  eopkg-Suricata:
    image: jasonish/suricata:latest
    container_name: eopkg-Suricata
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    volumes:
      - ./docker/sudo-eopkg-Vanguard/eopkg-Suricata:/var/lib/suricata
    restart: unless-stopped

  eopkg-Vault:
    image: hashicorp/vault:latest
    container_name: eopkg-Vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=aptlantis-root
    volumes:
      - ./docker/sudo-eopkg-Vanguard/eopkg-Vault:/vault/config
    cap_add:
      - IPC_LOCK
    networks:
      - sudo-eopkg-Vanguard
    restart: unless-stopped

  eopkg-ConsulTemplate:
    image: hashicorp/consul-template
    container_name: eopkg-ConsulTemplate
    volumes:
      - ./docker/sudo-eopkg-Vanguard/eopkg-ConsulTemplate:/etc/consul-template
    networks:
      - sudo-eopkg-Vanguard
    restart: unless-stopped

  eopkg-LogExporter:
    image: grafana/promtail:latest
    container_name: eopkg-LogExporter
    volumes:
      - /var/log:/var/log:ro
      - ./docker/sudo-eopkg-Vanguard/eopkg-LogExporter:/etc/promtail
    networks:
      - sudo-eopkg-Vanguard
    restart: unless-stopped

networks:
  sudo-eopkg-Vanguard:
    name: sudo-eopkg-Vanguard