services:
  apt-imageprocessor:
    container_name: apt-imageprocessor
    build: .
    networks:
      - sudo-apt-Conventicle
    volumes:
      - ./data:/data
    ports:
      - "8080:8000"  # HTTP API
    restart: unless-stopped

networks:
  sudo-apt-Conventicle:

